apiVersion: 1

deleteDatasources:
  - name: Postgres
    orgId: 1
  - name: Prometheus
    orgId: 1

datasources:
  - name: Postgres
    type: postgres
    url: postgres:5432
    user: user
    secureJsonData:
      password: password
    jsonData:
      database: content_platform
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      timeInterval: "15s"
